### PR TITLE
issue 19: RefactorRoboFile in to support classes

### PR DESCRIPTION
**Pull request by FatherShawn**
This PR moves all of the work out of RoboFile into command classes.  The commands are aggregated with a front controller script as documented at https://robo.li/framework/#using-multiple-robofiles-in-a-standalone-application

I think two levels of evaluation are needed:

1. The architecture and code: is it easier to understand and maintain?
2. Did we break anything with this change?

### CODE REVIEW

**Comment by FatherShawn** [comment]
Needs work: https://github.com/digitalpulp/ballast/issues/19#issuecomment-383141486

**Comment by FatherShawn** [comment]
Commands are now running properly - This PR is ready for local testing

**Comment by samtny** [comment]
How do I test this PR?  Do I just clone the github repo and checkout the branch, or... ?  thx.

**Comment by FatherShawn** [comment]
Yes: https://help.github.com/articles/checking-out-pull-requests-locally/
To test (2) above, checkout this PR, run `composer install` and see if you can work with the Drupal site as expected.

Thanks!

**Comment by FatherShawn** [comment]
`ERROR: Uncaught Error: Call to a member function getDrupalRoot() on null in /Users/shawnduncan/DockerSites/ballast/scripts/robo/src/Commands/DockerCommands.php:131`

**Comment by FatherShawn** [comment]
I cloned this branch and used it to convert a site over to Ballast.  I believe I've captured the discovered bug fixes into the PR.

**Comment by FatherShawn** [comment]
Discussed at weekly meeting - merging but not making a release pending another round of testing.

**Pull request merged**
